#!/usr/bin/env python3
"""
Process plugin param scan output files and generate:
1. A structured JSON database of all plugin params
2. A MacroMapper.cpp update snippet
3. Updated plugin lookup markdown docs

Usage: python3 tools/process_plugin_params.py
"""

import os, json, re, subprocess, sys
from pathlib import Path

SCANNER = "./build/ScanPluginParams_artefacts/Debug/ScanPluginParams"
PARAMS_DIR = Path("files/plugin_params")
PARAMS_DIR.mkdir(parents=True, exist_ok=True)

# ─────────────────────────────────────────────────────────────────────────────
# The plugins we care about, grouped by role
# ─────────────────────────────────────────────────────────────────────────────
PLUGINS = {
    # Channel strips
    "Console 1":                   "/Library/Audio/Plug-Ins/VST3/Console 1.vst3",
    "Weiss DS1-MK3":               "/Library/Audio/Plug-Ins/VST3/Weiss DS1-MK3.vst3",
    "Weiss EQ1":                   "/Library/Audio/Plug-Ins/VST3/Weiss EQ1.vst3",
    "Weiss EQ MP":                 "/Library/Audio/Plug-Ins/VST3/Weiss EQ MP.vst3",
    "Summit Audio Grand Channel":  "/Library/Audio/Plug-Ins/VST3/Summit Audio Grand Channel.vst3",
    "Pre 1973":                    "/Library/Audio/Plug-Ins/VST3/Pre 1973.vst3",
    "UA Century Channel":          "/Library/Audio/Plug-Ins/VST3/uaudio_century_channel_strip.vst3",
    "UA Manley VoxBox":            "/Library/Audio/Plug-Ins/VST3/uaudio_manley_voxbox.vst3",
    # Compressors / dynamics
    "UA Fairchild 670":            "/Library/Audio/Plug-Ins/VST3/uaudio_fairchild_670.vst3",
    "UA 1176LN Rev E":             "/Library/Audio/Plug-Ins/VST3/uaudio_ua_1176ln_rev_e.vst3",
    "Weiss MM-1 Mastering Maximizer": "/Library/Audio/Plug-Ins/VST3/Weiss MM-1 Mastering Maximizer.vst3",
    "soothe2":                     "/Library/Audio/Plug-Ins/VST3/soothe2.vst3",
    "Transient Shaper":            "/Library/Audio/Plug-Ins/VST3/Transient Shaper.vst3",
    # Reverbs / time-based
    "ValhallaRoom":                "/Library/Audio/Plug-Ins/VST3/ValhallaRoom.vst3",
    "ValhallaVintageVerb":         "/Library/Audio/Plug-Ins/VST3/ValhallaVintageVerb.vst3",
    # Instruments
    "Surge XT":                    "/Library/Audio/Plug-Ins/VST3/Surge XT.vst3",
    "Monoment Bass":               "/Library/Audio/Plug-Ins/VST3/Monoment Bass.vst3",
    "Statement Lead":              "/Library/Audio/Plug-Ins/VST3/Statement Lead.vst3",
    "Kick 3":                      "/Library/Audio/Plug-Ins/VST3/Kick 3.vst3",
    "SubLabXL":                    "/Library/Audio/Plug-Ins/VST3/SubLabXL.vst3",
    "Portal":                      "/Library/Audio/Plug-Ins/VST3/Portal.vst3",
}

def scan_plugin(path: str) -> list[dict]:
    """Run the scanner in JSON mode and parse result."""
    try:
        result = subprocess.run(
            [SCANNER, path, "json"],
            capture_output=True, text=True, timeout=15
        )
        raw = result.stdout
        # Strip any header lines before the JSON array
        idx = raw.find("[")
        if idx < 0:
            return []
        return json.loads(raw[idx:])
    except Exception as e:
        print(f"  ERROR: {e}", file=sys.stderr)
        return []

def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")

# ─────────────────────────────────────────────────────────────────────────────
# Scan all plugins and save individual JSON files
# ─────────────────────────────────────────────────────────────────────────────
all_params: dict[str, list[dict]] = {}

for name, path in PLUGINS.items():
    slug = slugify(name)
    json_path = PARAMS_DIR / f"{slug}.json"
    
    if not os.path.exists(path):
        print(f"SKIP (not installed): {name}")
        continue
    
    print(f"Scanning: {name} ...", end=" ", flush=True)
    params = scan_plugin(path)
    
    if params:
        all_params[name] = params
        with open(json_path, "w") as f:
            json.dump(params, f, indent=2)
        print(f"OK ({len(params)} params)")
    else:
        print("FAILED or 0 params")

# ─────────────────────────────────────────────────────────────────────────────
# Save combined database
# ─────────────────────────────────────────────────────────────────────────────
combined_path = PARAMS_DIR / "_all_plugins.json"
with open(combined_path, "w") as f:
    json.dump(all_params, f, indent=2)
print(f"\nSaved combined DB: {combined_path}")

# ─────────────────────────────────────────────────────────────────────────────
# Generate human-readable parameter reference for each plugin
# ─────────────────────────────────────────────────────────────────────────────
ref_lines = ["# Plugin Parameter Reference\n\nGenerated by `tools/process_plugin_params.py`\n"]

for name, params in all_params.items():
    ref_lines.append(f"\n## {name}\n")
    ref_lines.append("```")
    ref_lines.append(f"{'IDX':<4}  {'NAME':<40}  {'ID':<20}  DEFAULT  STEPS")
    ref_lines.append(f"{'---':<4}  {'----':<40}  {'--':<20}  -------  -----")
    for p in params:
        steps = f"[{p['numSteps']}]" if p.get("numSteps", 0) > 1 else ""
        ref_lines.append(
            f"{p['index']:<4}  {p['name']:<40}  {p.get('id',''):<20}  {p['default']:7.3f}  {steps}"
        )
    ref_lines.append("```\n")

ref_path = PARAMS_DIR / "README.md"
with open(ref_path, "w") as f:
    f.write("\n".join(ref_lines))
print(f"Saved reference doc: {ref_path}")

# ─────────────────────────────────────────────────────────────────────────────
# Print a focused summary of sidechain-relevant params for each plugin
# ─────────────────────────────────────────────────────────────────────────────
print("\n\n=== SIDECHAIN / COMPRESSOR KEY PARAMS ===\n")
SC_KEYWORDS = ["compress", "threshold", "ratio", "attack", "release", "sidechain", "sc ", "gain", "limit"]

for name, params in all_params.items():
    relevant = [p for p in params if any(k in p["name"].lower() for k in SC_KEYWORDS)]
    if relevant:
        print(f"\n{name}:")
        for p in relevant:
            steps_str = f" [{p['numSteps']} steps]" if p.get("numSteps", 0) > 1 else ""
            print(f"  {p['index']:3}  {p['name']:<40}  default={p['default']:.3f}{steps_str}")
